create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  preferred_language text default 'en',
  role text default 'reader' check (role in ('reader', 'editor', 'admin')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.saved_articles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null,
  title text not null,
  link text not null,
  source text,
  category text,
  summary text,
  image_url text,
  published_at timestamptz,
  created_at timestamptz default now(),
  unique(user_id, article_id)
);

create table if not exists public.reading_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null,
  title text not null,
  link text not null,
  source text,
  category text,
  read_at timestamptz default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  language text default 'en',
  status text default 'active' check (status in ('active', 'unsubscribed')),
  source text default 'site',
  created_at timestamptz default now()
);

create table if not exists public.rss_sources (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  url text not null unique,
  language text default 'en',
  country text default 'IN',
  enabled boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.adsense_slots (
  id uuid primary key default gen_random_uuid(),
  slot_key text unique not null,
  placement text not null,
  format text not null,
  enabled boolean default true,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.affiliate_links (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  destination_url text not null,
  disclosure text default 'Nuzenio may earn a commission from this link.',
  enabled boolean default false,
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  article_id text,
  category text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.saved_articles enable row level security;
alter table public.reading_history enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.rss_sources enable row level security;
alter table public.adsense_slots enable row level security;
alter table public.affiliate_links enable row level security;
alter table public.analytics_events enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

create policy "Profiles are readable by owner"
on public.profiles for select using (auth.uid() = id);

create policy "Users update own profile"
on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Users can manage own saved articles"
on public.saved_articles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage own reading history"
on public.reading_history for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Anyone can subscribe to newsletter"
on public.newsletter_subscribers for insert with check (true);

create policy "Subscribers can read own email row"
on public.newsletter_subscribers for select using (auth.jwt() ->> 'email' = email);

create policy "RSS sources are publicly readable"
on public.rss_sources for select using (enabled = true);

create policy "Ad slots are publicly readable"
on public.adsense_slots for select using (enabled = true);

create policy "Approved affiliate links are publicly readable"
on public.affiliate_links for select using (enabled = true);

create policy "Users can insert analytics events"
on public.analytics_events for insert with check (auth.uid() = user_id or user_id is null);

create policy "Admins can manage profiles"
on public.profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage rss sources"
on public.rss_sources for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage ad slots"
on public.adsense_slots for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage affiliate links"
on public.affiliate_links for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can read newsletter subscribers"
on public.newsletter_subscribers for select
using (public.is_admin());

create policy "Admins can read analytics events"
on public.analytics_events for select
using (public.is_admin());

create index if not exists saved_articles_user_idx on public.saved_articles(user_id, created_at desc);
create index if not exists reading_history_user_idx on public.reading_history(user_id, read_at desc);
create index if not exists newsletter_language_idx on public.newsletter_subscribers(language, created_at desc);
create index if not exists analytics_event_idx on public.analytics_events(event_name, created_at desc);
create index if not exists affiliate_category_idx on public.affiliate_links(category, enabled);

insert into public.rss_sources (name, category, url, language, country)
values
  ('Google News India Local', 'local', 'https://news.google.com/rss/search?q=India&hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN'),
  ('Google News US Local', 'local', 'https://news.google.com/rss/search?q=United%20States&hl=en-US&gl=US&ceid=US:en', 'en', 'US'),
  ('Google News India Top', 'top', 'https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN'),
  ('Google News World', 'world', 'https://news.google.com/rss/headlines/section/topic/WORLD?hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN')
on conflict (url) do nothing;

insert into public.adsense_slots (slot_key, placement, format, notes)
values
  ('top-native', 'Home feed top', 'native', 'Reserved until AdSense approval.'),
  ('sidebar-rectangle', 'Desktop right rail', 'rectangle', 'Reserved until AdSense approval.'),
  ('article-inline', 'Article detail body', 'responsive', 'Add publisher script after policy review.'),
  ('mobile-feed', 'Mobile feed after story cards', 'responsive', 'Mobile-first revenue slot.'),
  ('newsletter-sponsor', 'Daily brief sponsorship', 'sponsor', 'Sponsor slot for newsletter campaigns.')
on conflict (slot_key) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
